### ISSUE TITLE
Display tables according to data in business model

### ISSUE THREAD

**Issue by crc83** [crc83/WebCash#16]
Display tables in order that got from business model i.e.
In managed bean constructor define stub data of two halls and tables in it.
It should be possible ot swich betwen halls and choose appropriate table

Table shoul have coordinates, and name
Hall should have a name

**Comment by Colyas** [comment]
Знаю як додати картинку не знаю як зробити джава метод з координатами картинки

**Comment by crc83** [comment]
Related issue is #31. So I close this issue as duplicate
