### ISSUE TITLE
Evaluate possibility to print long checks and reports

### ISSUE THREAD

**Issue by crc83** [crc83/WebCash#28]
At first time let's evaluate two tools:
1) JasperReport
2) BIRT
I will get two printers for this reason soon

**Comment by Colyas** [comment]
http://www.vogella.com/articles/EclipseBIRT/article.html - Reporting with Eclipse BIRT and Java Objects

**Comment by crc83** [comment]
JasperReport
1) Hierarchical reports described here : http://www.richardnichols.net/2010/02/simple-guide-to-sub-reports-in-jasperreports-ireport/
2) we can use alignment of fields in JasperReport (Layout : Strech or something like this)

**Comment by Colyas** [comment]
http://jasperreports.sourceforge.net/JasperReports-Ultimate-Guide-3.pdf - 81 page
http://www.jasperassistant.com/forum/topic/11115/jasperreport_subreport_inside_subreport

**Comment by Colyas** [comment]
.ignorePagination(true)
